addons/opt_weapons/config.cpp
mod.cpp

Mod Update V2.82

---

addons/opt_characters/$PBOPREFIX$

Hab bei einem Rename versagt, so dass es nicht funktionieren konnte.
Danke an @formtapez für den Hinweis!

Urgent fix opt_characters pboprefix

---

addons/opt_vehicles/heli/config.cpp
addons/opt_weapons/config.cpp

Hummingbird bekommt 30 Flares
closes #49

Flares MH-9

---

addons/opt_core/dialogs/OPTDef.hpp
addons/opt_gps/dialogs/config.cpp

Fix des Mini GPS durch Zusatz Dialog

GPS Fix MiniGPS

---

addons/opt_vehicles/heli/config.cpp

Inventar des Taru Rep geleert.

FIx Inventar Taru Rep

---

addons/opt_vehicles/apc/config.cpp
addons/opt_vehicles/cars/config.cpp
addons/opt_vehicles/heli/config.cpp
addons/opt_vehicles/mbt/config.cpp
addons/opt_vehicles/plane/config.cpp
addons/opt_vehicles/truck/config.cpp
addons/opt_vehicles/uav/config.cpp
addons/opt_weapons/config.cpp
mod.cpp

[WIP]Änderungen Kampagne 2021

---

addons/opt_vehicles/truck/config.cpp
mod.cpp

Zamak Sani LKWs hinzugefügt CSAT + AAF

Zamak Sani LKWs hinzugefügt

---

addons/weapons/config.cpp

Fixes Tests

---

addons/characters/config.cpp
addons/vehicles/apc/config.cpp
addons/vehicles/cars/config.cpp
addons/vehicles/heli/config.cpp
addons/vehicles/mbt/config.cpp
addons/vehicles/plane/config.cpp
addons/vehicles/truck/config.cpp
addons/weapons/config.cpp

Treibstoff Menge
https://opt4.net/forum/index.php?thread/5284-%C3%A4nderungen-mod-kampage-2h2021-treibstoffmenge/&postID=105152#post105152
Fixes

Test Änderung / Fixes

---

addons/main/script_version.hpp
addons/weapons/config.cpp

Anderungen kampage 2 h2021

---

addons/characters/config.cpp
addons/vehicles/apc/config.cpp
addons/vehicles/cars/config.cpp
addons/vehicles/mbt/config.cpp
addons/weapons/config.cpp

Fix und Änderungen Techschlacht 1

---

hemtt.toml

HEMTT Extras

---

addons/weapons/config.cpp

Fixes Clientmod 

---

.gitignore
addons/characters/config.cpp
addons/weapons/config.cpp

Fixes : Feedback für TC3

---

addons/characters/config.cpp
addons/vehicles/heli/config.cpp
addons/weapons/config.cpp

Wenn kein Veto komm übernehmen für TC3
Hatte das mit Schrecki wegen der Raketen beredet.

Weitere Fixes nach Feedback und Bugmeldung 

---

addons/characters/config.cpp
addons/main/script_version.hpp
addons/vehicles/heli/config.cpp
addons/weapons/config.cpp

Feedback und Bugfix  tc4

---

addons/core/CfgVideoOptions.hpp
addons/core/config.cpp
addons/main/script_version.hpp

ATOC einstellungen

---

addons/weapons/config.cpp

Konzeptantrag Gewehre für Schütze

---

addons/intro/dialogs/config.cpp
addons/main/script_version.hpp

Nacharbeiten 2022 cheranrus

---

addons/characters/config.cpp
addons/main/script_version.hpp

Fix uniformen

---

addons/vehicles/boat/config.cpp
addons/vehicles/heli/config.cpp
addons/vehicles/truck/config.cpp
addons/weapons/config.cpp

Änderungen TC5

---

addons/main/script_version.hpp
addons/vehicles/uav/config.cpp

Fix2 UAV Pelican Drohne

---

addons/characters/config.cpp
addons/main/script_version.hpp

Abschlussarbeiten 2022 H2

---

addons/characters/config.cpp
addons/main/script_version.hpp

Bugfix MM1 2022
